/**
 * autoSeed.js — Runs on server startup if DB is empty. Safe for production.
 */
const bcrypt = require('bcryptjs');
const User = require('../models/User');
const Property = require('../models/Property');
const Review = require('../models/Review');
const Booking = require('../models/Booking');

const autoSeed = async () => {
  try {
    const count = await Property.countDocuments();
    const offerCount = await Property.countDocuments({ 'offer.isActive': true });

    if (count > 0 && offerCount >= 6) {
      console.log(`✅ DB has ${count} properties (${offerCount} offer deals) — skipping auto-seed.`);
      return;
    }

    let landlordUser = await User.findOne({ role: 'landlord' }) || await User.findOne();
    let tenantUsers = await User.find({ role: 'tenant' });

    if (count === 0 || !landlordUser) {
      console.log('🌱 Empty DB or missing users detected — running full auto-seed reset...');

      await User.deleteMany();
      await Property.deleteMany();
      await Review.deleteMany();
      await Booking.deleteMany();

      const salt = await bcrypt.genSalt(10);
      const hashedPassword = await bcrypt.hash('password123', salt);

      const users = await User.insertMany([
        { name: 'Admin User',    email: 'admin@airental.com',    password: hashedPassword, role: 'admin',    isVerified: true, avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Admin' },
        { name: 'John Landlord', email: 'landlord@airental.com', password: hashedPassword, role: 'landlord', isVerified: true, avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John' },
        { name: 'Jane Tenant',   email: 'tenant@airental.com',   password: hashedPassword, role: 'tenant',   isVerified: true, avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane' },
        { name: 'Alice Smith',   email: 'tenant2@airental.com',  password: hashedPassword, role: 'tenant',   isVerified: true, avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alice' },
        { name: 'Bob Johnson',   email: 'tenant3@airental.com',  password: hashedPassword, role: 'tenant',   isVerified: true, avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bob' },
        { name: 'Charlie Davis', email: 'tenant4@airental.com',  password: hashedPassword, role: 'tenant',   isVerified: true, avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Charlie' },
      ]);

      landlordUser = users[1];
      tenantUsers  = [users[2], users[3], users[4], users[5]];
    }

    const landlordId = landlordUser._id;
    const tenantIds  = tenantUsers.map(u => u._id);

    const propertiesData = [
      { title: 'Cozy Studio Near Tech Park', description: 'Perfect studio for tech professionals near Tech Park. Fully furnished with modern amenities.', propertyType: 'studio', status: 'available', isVerified: true, price: { amount: 15000, currency: 'INR', period: 'monthly' }, location: { address: '123 Tech Avenue, Whitefield', city: 'Bangalore', state: 'Karnataka', pincode: '560001', coordinates: { lat: 12.9716, lng: 77.5946 } }, features: { bedrooms: 0, bathrooms: 1, area: 300, furnished: 'fully-furnished', parking: true, petFriendly: false }, amenities: ['WiFi', 'AC', 'Kitchen', 'CCTV Security', 'Parking'], bookingDetails: { minStay: 1, maxStay: 365, checkIn: '2:00 PM', checkOut: '11:00 AM', cancellationPolicy: 'Free cancellation up to 7 days', securityDeposit: 30000, extraCharges: 'No extra charges.', houseRules: ['No smoking', 'No loud music after 10 PM'] }, aiDescription: 'Ideal studio for tech professionals in Whitefield.', images: [{ url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop&q=80' }, { url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop&q=80' }] },
      { title: 'Luxury 2BHK Apartment Downtown', description: 'Spacious luxurious 2 bedroom apartment in downtown. Modern amenities and stunning city views.', propertyType: 'apartment', status: 'available', isVerified: true, price: { amount: 45000, currency: 'INR', period: 'monthly' }, location: { address: '456 Downtown Plaza, Bandra West', city: 'Mumbai', state: 'Maharashtra', pincode: '400050', coordinates: { lat: 19.0760, lng: 72.8777 } }, features: { bedrooms: 2, bathrooms: 2, area: 1200, furnished: 'fully-furnished', parking: true, petFriendly: true }, amenities: ['Gym', 'Pool', 'WiFi', '24/7 Security', 'Parking', 'Smart TV'], bookingDetails: { minStay: 3, maxStay: 365, checkIn: '2:00 PM', checkOut: '11:00 AM', cancellationPolicy: '50% refund if cancelled 14 days before', securityDeposit: 90000, extraCharges: 'Utilities included.', houseRules: ['No smoking', 'Quiet hours: 10 PM - 8 AM'] }, aiDescription: 'Premium 2BHK in Bandra West with skyline views.', images: [{ url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop&q=80' }, { url: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800&h=600&fit=crop&q=80' }] },
      { title: 'Modern 3BHK Villa with Garden', description: 'Beautiful 3 bedroom villa with spacious garden. Modern architecture. Ideal for families.', propertyType: 'villa', status: 'available', isVerified: true, price: { amount: 80000, currency: 'INR', period: 'monthly' }, location: { address: '789 Garden Lane, Vasant Kunj', city: 'Delhi', state: 'Delhi', pincode: '110070', coordinates: { lat: 28.7041, lng: 77.1025 } }, features: { bedrooms: 3, bathrooms: 3, area: 2500, furnished: 'semi-furnished', parking: true, petFriendly: true }, amenities: ['Garden', 'Garage', 'Terrace', 'WiFi', 'Solar Power', 'Security Gate'], bookingDetails: { minStay: 6, maxStay: 365, checkIn: '1:00 PM', checkOut: '12:00 PM', cancellationPolicy: 'Free cancellation 30 days before', securityDeposit: 160000, extraCharges: 'Utilities: Rs.5000-8000/month.', houseRules: ['No parties', 'Maintain garden'] }, aiDescription: 'Spacious family villa in secure Vasant Kunj.', images: [{ url: 'https://images.unsplash.com/photo-1570129477492-45a003537e1b?w=800&h=600&fit=crop&q=80' }, { url: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop&q=80' }] },
      { title: 'Cozy 1BHK Near University', description: 'Perfect for students. Affordable 1 bedroom near campus with all amenities.', propertyType: 'apartment', status: 'available', isVerified: false, price: { amount: 18000, currency: 'INR', period: 'monthly' }, location: { address: '321 University Road, Deccan Gymkhana', city: 'Pune', state: 'Maharashtra', pincode: '411004', coordinates: { lat: 18.5204, lng: 73.8567 } }, features: { bedrooms: 1, bathrooms: 1, area: 450, furnished: 'fully-furnished', parking: false, petFriendly: false }, amenities: ['WiFi', 'AC', 'Study Table', 'Kitchen', 'CCTV Security'], bookingDetails: { minStay: 1, maxStay: 180, checkIn: '12:00 PM', checkOut: '11:00 AM', cancellationPolicy: 'Free cancellation 5 days before', securityDeposit: 20000, extraCharges: 'Electricity as per sub-meter.', houseRules: ['No loud music', 'No smoking'] }, aiDescription: 'Student housing near colleges in Pune.', images: [{ url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop&q=80' }, { url: 'https://images.unsplash.com/photo-1523217311519-d595dc36ab0b?w=800&h=600&fit=crop&q=80' }] },
      { title: 'Premium Penthouse with City View', description: 'Exclusive penthouse with breathtaking city views. Rooftop terrace included.', propertyType: 'penthouse', status: 'available', isVerified: true, price: { amount: 150000, currency: 'INR', period: 'monthly' }, location: { address: '999 Sky Tower, Indira Nagar', city: 'Bangalore', state: 'Karnataka', pincode: '560038', coordinates: { lat: 12.9752, lng: 77.6245 } }, features: { bedrooms: 3, bathrooms: 3, area: 3500, furnished: 'fully-furnished', parking: true, petFriendly: true }, amenities: ['Rooftop Terrace', 'Home Theater', 'Gym', 'Smart Home', 'Concierge', 'Spa Bath'], bookingDetails: { minStay: 12, maxStay: 365, checkIn: '3:00 PM', checkOut: '11:00 AM', cancellationPolicy: '60 days notice required', securityDeposit: 300000, extraCharges: 'All utilities included.', houseRules: ['Concierge coordination for events'] }, aiDescription: 'Luxury penthouse in central Indira Nagar.', images: [{ url: 'https://images.unsplash.com/photo-1512207736139-c1957dd8ded5?w=800&h=600&fit=crop&q=80' }, { url: 'https://images.unsplash.com/photo-1493857671505-72967e2e2760?w=800&h=600&fit=crop&q=80' }] },
      { title: 'Spacious House with Backyard', description: 'Charming 2 bedroom house with large backyard. Close to schools and markets.', propertyType: 'house', status: 'available', isVerified: false, price: { amount: 35000, currency: 'INR', period: 'monthly' }, location: { address: '555 Suburban Lane, Gachibowli', city: 'Hyderabad', state: 'Telangana', pincode: '500032', coordinates: { lat: 17.3850, lng: 78.4867 } }, features: { bedrooms: 2, bathrooms: 2, area: 1800, furnished: 'semi-furnished', parking: true, petFriendly: true }, amenities: ['Backyard', 'Garage', 'Kitchen Garden', 'WiFi'], bookingDetails: { minStay: 6, maxStay: 365, checkIn: '2:00 PM', checkOut: '11:00 AM', cancellationPolicy: 'Free cancellation 14 days before', securityDeposit: 70000, extraCharges: 'Gardener fee: Rs.1500/month.', houseRules: ['Maintain backyard', 'Pets allowed'] }, aiDescription: 'Family home in suburban Gachibowli.', images: [{ url: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop&q=80' }, { url: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&h=600&fit=crop&q=80' }] },
      { title: 'Elegant Condo in Prime Location', description: 'Sophisticated 2 bedroom condo. Walking distance to shops and entertainment.', propertyType: 'condo', status: 'available', isVerified: true, price: { amount: 55000, currency: 'INR', period: 'monthly' }, location: { address: '222 Business District, T Nagar', city: 'Chennai', state: 'Tamil Nadu', pincode: '600017', coordinates: { lat: 13.0489, lng: 80.2506 } }, features: { bedrooms: 2, bathrooms: 2, area: 1400, furnished: 'fully-furnished', parking: true, petFriendly: false }, amenities: ['Elevator', 'Security', 'Gym', 'Lounge', 'WiFi', 'Modular Kitchen'], bookingDetails: { minStay: 2, maxStay: 365, checkIn: '2:00 PM', checkOut: '11:00 AM', cancellationPolicy: '30% refund if cancelled 10 days before', securityDeposit: 110000, extraCharges: 'Utilities: Rs.3000-4000/month.', houseRules: ['Quiet hours after 10 PM'] }, aiDescription: 'Modern condo in T Nagar, Chennai.', images: [{ url: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800&h=600&fit=crop&q=80' }, { url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop&q=80' }] },
      { title: 'Modern Loft in Arts District', description: 'Trendy loft with high ceilings and exposed brick. Perfect for creatives.', propertyType: 'apartment', status: 'available', isVerified: true, price: { amount: 42000, currency: 'INR', period: 'monthly' }, location: { address: '111 Art Street, Indiranagar', city: 'Bangalore', state: 'Karnataka', pincode: '560034', coordinates: { lat: 12.9698, lng: 77.6357 } }, features: { bedrooms: 1, bathrooms: 1, area: 700, furnished: 'fully-furnished', parking: true, petFriendly: true }, amenities: ['High Ceilings', 'Exposed Brick', 'WiFi', 'Gallery Space', 'Workspace'], bookingDetails: { minStay: 1, maxStay: 365, checkIn: '12:00 PM', checkOut: '11:00 AM', cancellationPolicy: 'Free cancellation 5 days before', securityDeposit: 84000, extraCharges: 'Utilities: Rs.2500-3500/month.', houseRules: ['Respect artistic community'] }, aiDescription: 'Warehouse loft in Indiranagar Arts district.', images: [{ url: 'https://images.unsplash.com/photo-1493857671505-72967e2e2760?w=800&h=600&fit=crop&q=80' }, { url: 'https://images.unsplash.com/photo-1540932239986-310128078ceb?w=800&h=600&fit=crop&q=80' }] },
      { title: 'Beach View Apartment', description: 'Beautiful apartment with stunning beach views. Wake up to the sound of waves.', propertyType: 'apartment', status: 'available', isVerified: true, price: { amount: 65000, currency: 'INR', period: 'monthly' }, location: { address: '222 Beachfront Road, Anjuna', city: 'Goa', state: 'Goa', pincode: '403509', coordinates: { lat: 15.5804, lng: 73.7423 } }, features: { bedrooms: 2, bathrooms: 2, area: 1300, furnished: 'fully-furnished', parking: true, petFriendly: true }, amenities: ['Beach Access', 'Balcony', 'AC', 'WiFi', 'CCTV Security'], bookingDetails: { minStay: 3, maxStay: 90, checkIn: '1:00 PM', checkOut: '10:00 AM', cancellationPolicy: 'Full refund if cancelled 7 days before', securityDeposit: 50000, extraCharges: 'Cleaning: Rs.1000 per stay.', houseRules: ['Quiet hours after 11 PM'] }, aiDescription: 'Beachfront property in Anjuna, Goa.', images: [{ url: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=800&h=600&fit=crop&q=80' }, { url: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&h=600&fit=crop&q=80' }] },
      { title: 'Green Living - Eco Apartment', description: 'Sustainable eco-friendly apartment with solar panels and water harvesting.', propertyType: 'apartment', status: 'available', isVerified: true, price: { amount: 38000, currency: 'INR', period: 'monthly' }, location: { address: '333 Green Lane, Kalyani Nagar', city: 'Pune', state: 'Maharashtra', pincode: '411006', coordinates: { lat: 18.5489, lng: 73.9006 } }, features: { bedrooms: 2, bathrooms: 2, area: 950, furnished: 'fully-furnished', parking: true, petFriendly: false }, amenities: ['Solar Power', 'Water Harvesting', 'Garden', 'WiFi', 'Air Purifier'], bookingDetails: { minStay: 3, maxStay: 365, checkIn: '2:00 PM', checkOut: '11:00 AM', cancellationPolicy: '40% refund if cancelled 15 days before', securityDeposit: 76000, extraCharges: 'Utilities reduced due to solar.', houseRules: ['Follow eco-friendly practices'] }, aiDescription: 'Eco-optimized property in Kalyani Nagar.', images: [{ url: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop&q=80' }, { url: 'https://images.unsplash.com/photo-1587584622649-fb0be0d52364?w=800&h=600&fit=crop&q=80' }] },
      { title: 'Luxury Serviced Apartment', description: 'Premium serviced apartment with housekeeping and room service. Hotel-like comfort.', propertyType: 'apartment', status: 'available', isVerified: true, price: { amount: 75000, currency: 'INR', period: 'monthly' }, location: { address: '444 Business Tower, Worli', city: 'Mumbai', state: 'Maharashtra', pincode: '400018', coordinates: { lat: 19.0176, lng: 72.8479 } }, features: { bedrooms: 2, bathrooms: 2, area: 1400, furnished: 'fully-furnished', parking: true, petFriendly: false }, amenities: ['Housekeeping', 'Laundry', 'Room Service', 'Gym', 'Pool', 'Business Center', 'WiFi'], bookingDetails: { minStay: 1, maxStay: 365, checkIn: 'Flexible', checkOut: 'Flexible', cancellationPolicy: 'No charge for cancellations', securityDeposit: 150000, extraCharges: 'All-inclusive: housekeeping, laundry, utilities.', houseRules: ['No parties', 'Corporate verification required'] }, aiDescription: 'Corporate grade serviced residence in Worli.', images: [{ url: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800&h=600&fit=crop&q=80' }, { url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop&q=80' }] },
      { title: 'Converted Warehouse Loft', description: 'Stunning warehouse with industrial charm. Open spaces and skylights.', propertyType: 'apartment', status: 'available', isVerified: true, price: { amount: 55000, currency: 'INR', period: 'monthly' }, location: { address: '555 Industrial Avenue, Okhla', city: 'Delhi', state: 'Delhi', pincode: '110020', coordinates: { lat: 28.5244, lng: 77.2458 } }, features: { bedrooms: 2, bathrooms: 2, area: 1600, furnished: 'semi-furnished', parking: true, petFriendly: true }, amenities: ['High Ceilings', 'Skylights', 'Workspace', 'Parking', 'Large Windows'], bookingDetails: { minStay: 2, maxStay: 365, checkIn: '1:00 PM', checkOut: '11:00 AM', cancellationPolicy: 'Flexible - 7 days notice', securityDeposit: 110000, extraCharges: 'Utilities: Rs.3000-4000/month.', houseRules: ['No structural modifications'] }, aiDescription: 'Warehouse loft conversion in Okhla.', images: [{ url: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&h=600&fit=crop&q=80' }, { url: 'https://images.unsplash.com/photo-1512917774080-9b41b20b7487?w=800&h=600&fit=crop&q=80' }] },
      { title: 'Family Villa with Pool', description: 'Spacious family villa with private pool and landscaped garden.', propertyType: 'villa', status: 'available', isVerified: true, price: { amount: 95000, currency: 'INR', period: 'monthly' }, location: { address: '666 Luxury Lane, Jubilee Hills', city: 'Hyderabad', state: 'Telangana', pincode: '500033', coordinates: { lat: 17.4304, lng: 78.4067 } }, features: { bedrooms: 4, bathrooms: 3, area: 3200, furnished: 'semi-furnished', parking: true, petFriendly: true }, amenities: ['Swimming Pool', 'Garden', 'Garage', 'Terrace', 'BBQ Area', 'Security System'], bookingDetails: { minStay: 6, maxStay: 365, checkIn: '2:00 PM', checkOut: '12:00 PM', cancellationPolicy: 'Non-refundable deposit', securityDeposit: 190000, extraCharges: 'Pool maintenance: Rs.3000/month.', houseRules: ['Pool safety rules enforced'] }, aiDescription: '4BHK family villa in Jubilee Hills.', images: [{ url: 'https://images.unsplash.com/photo-1570129477492-45a003537e1b?w=800&h=600&fit=crop&q=80' }, { url: 'https://images.unsplash.com/photo-1576941089067-2de3dd21bfb0?w=800&h=600&fit=crop&q=80' }] },
      { title: 'Smart Home Tech Apartment', description: 'IoT smart home — control lights, AC and security from your phone.', propertyType: 'apartment', status: 'available', isVerified: true, price: { amount: 68000, currency: 'INR', period: 'monthly' }, location: { address: '777 Tech Park, Outer Ring Road', city: 'Bangalore', state: 'Karnataka', pincode: '560103', coordinates: { lat: 12.9352, lng: 77.6245 } }, features: { bedrooms: 2, bathrooms: 2, area: 1100, furnished: 'fully-furnished', parking: true, petFriendly: false }, amenities: ['Smart Lights', 'Smart AC', 'Smart Lock', 'CCTV', 'High Speed WiFi', 'Robot Vacuum', 'Voice Assistant'], bookingDetails: { minStay: 2, maxStay: 365, checkIn: '2:00 PM', checkOut: '11:00 AM', cancellationPolicy: '20% refund if cancelled 10 days before', securityDeposit: 136000, extraCharges: 'Premium WiFi included.', houseRules: ['Treat tech equipment with care'] }, aiDescription: 'IoT-enabled apartment on Outer Ring Road.', images: [{ url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop&q=80' }, { url: 'https://images.unsplash.com/photo-1523217311519-d595dc36ab0b?w=800&h=600&fit=crop&q=80' }] },
      { title: 'Artist Studio Apartment', description: 'Creative studio with large windows for natural light. Gallery space included.', propertyType: 'studio', status: 'available', isVerified: false, price: { amount: 28000, currency: 'INR', period: 'monthly' }, location: { address: '888 Artist Lane, Malleshwaram', city: 'Bangalore', state: 'Karnataka', pincode: '560003', coordinates: { lat: 12.9989, lng: 77.5741 } }, features: { bedrooms: 0, bathrooms: 1, area: 600, furnished: 'semi-furnished', parking: true, petFriendly: true }, amenities: ['Large Windows', 'Gallery Space', 'Work Area', 'Kitchenette', 'WiFi'], bookingDetails: { minStay: 1, maxStay: 365, checkIn: '2:00 PM', checkOut: '12:00 PM', cancellationPolicy: 'Flexible cancellation', securityDeposit: 40000, extraCharges: 'Studio setup fee: Rs.2000 (optional).', houseRules: ['Do not damage walls'] }, aiDescription: 'Artist loft in Malleshwaram.', images: [{ url: 'https://images.unsplash.com/photo-1540932239986-310128078ceb?w=800&h=600&fit=crop&q=80' }, { url: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&h=600&fit=crop&q=80' }] },
      { title: 'Boutique Hotel Apartment', description: 'Heritage building apartment blending old-world charm with modern comfort.', propertyType: 'apartment', status: 'available', isVerified: true, price: { amount: 52000, currency: 'INR', period: 'monthly' }, location: { address: '999 Heritage Street, Mylapore', city: 'Chennai', state: 'Tamil Nadu', pincode: '600004', coordinates: { lat: 13.0289, lng: 80.2606 } }, features: { bedrooms: 2, bathrooms: 2, area: 1000, furnished: 'fully-furnished', parking: true, petFriendly: false }, amenities: ['Heritage Design', 'Rooftop Access', 'Library', 'Lounge', 'Cafe', 'Concierge', 'WiFi'], bookingDetails: { minStay: 3, maxStay: 365, checkIn: '2:00 PM', checkOut: '11:00 AM', cancellationPolicy: '50% refund if cancelled 14 days before', securityDeposit: 104000, extraCharges: 'Heritage tour included.', houseRules: ['Respect historical property'] }, aiDescription: 'Restored heritage home in Mylapore.', images: [{ url: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&h=600&fit=crop&q=80' }, { url: 'https://images.unsplash.com/photo-1576941089067-2de3dd21bfb0?w=800&h=600&fit=crop&q=80' }] },
      // ── 6 OFFER PROPERTIES ──
      { title: 'Skyline Studio — Zero Brokerage Deal', description: 'Brand new 18th floor studio with panoramic views. 25% off, zero brokerage, all utilities included.', propertyType: 'studio', status: 'available', isVerified: true, price: { amount: 18000, currency: 'INR', period: 'monthly' }, offer: { isActive: true, label: '🔥 Zero Brokerage + 25% Off — Never Expires', discountPercent: 25, originalPrice: 24000, badge: 'BESTSELLER' }, location: { address: '14 Skyline Towers, Koramangala 5th Block', city: 'Bangalore', state: 'Karnataka', pincode: '560095', coordinates: { lat: 12.9352, lng: 77.6245 } }, features: { bedrooms: 0, bathrooms: 1, area: 420, furnished: 'fully-furnished', parking: true, petFriendly: false }, amenities: ['High-Speed WiFi', 'Smart AC', 'Modular Kitchen', 'CCTV', 'Power Backup', 'Rooftop Access', 'Gym'], bookingDetails: { minStay: 1, maxStay: 365, checkIn: '12:00 PM', checkOut: '11:00 AM', cancellationPolicy: 'Free cancellation up to 7 days', securityDeposit: 18000, extraCharges: 'All utilities included. Zero brokerage.', houseRules: ['No smoking', 'No parties'] }, aiDescription: 'Premium studio in Koramangala — 25% below market, zero brokerage.', images: [{ url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop&q=80' }, { url: 'https://images.unsplash.com/photo-1512917774080-9b41b20b7487?w=800&h=600&fit=crop&q=80' }] },
      { title: 'Sea-Breeze 2BHK — First 3 Months Free Maintenance', description: '2-bedroom 300m from Juhu Beach. 20% off rent + free society maintenance for 3 months.', propertyType: 'apartment', status: 'available', isVerified: true, price: { amount: 52000, currency: 'INR', period: 'monthly' }, offer: { isActive: true, label: '🌊 20% Off + Free Maintenance — Ongoing Offer', discountPercent: 20, originalPrice: 65000, badge: 'HOT DEAL' }, location: { address: '7B Seaview Heights, Juhu Tara Road', city: 'Mumbai', state: 'Maharashtra', pincode: '400049', coordinates: { lat: 19.0990, lng: 72.8261 } }, features: { bedrooms: 2, bathrooms: 2, area: 1150, furnished: 'fully-furnished', parking: true, petFriendly: true }, amenities: ['Sea View Balcony', 'Wooden Flooring', 'WiFi', 'AC', 'Gym', 'Swimming Pool', '24/7 Security'], bookingDetails: { minStay: 3, maxStay: 365, checkIn: '2:00 PM', checkOut: '11:00 AM', cancellationPolicy: '50% refund if cancelled 14 days before', securityDeposit: 104000, extraCharges: 'First 3 months maintenance free.', houseRules: ['No loud music after 10 PM', 'Pets with deposit'] }, aiDescription: 'Coastal apartment near Juhu Beach — 20% off market.', images: [{ url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop&q=80' }, { url: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=800&h=600&fit=crop&q=80' }] },
      { title: 'Royal 4BHK Villa — 30% Off, Lifetime Price Lock', description: '4-bedroom gated villa with private pool. 30% off market + rent never increases.', propertyType: 'villa', status: 'available', isVerified: true, price: { amount: 84000, currency: 'INR', period: 'monthly' }, offer: { isActive: true, label: '👑 30% Off + Lifetime Price Lock — Exclusive', discountPercent: 30, originalPrice: 120000, badge: 'EXCLUSIVE' }, location: { address: '2 Maharaja Enclave, Sushant Lok Phase 1', city: 'Gurgaon', state: 'Haryana', pincode: '122002', coordinates: { lat: 28.4595, lng: 77.0266 } }, features: { bedrooms: 4, bathrooms: 4, area: 3800, furnished: 'semi-furnished', parking: true, petFriendly: true }, amenities: ['Private Pool', 'Garden', 'Servant Quarters', 'Home Theater', 'Solar Power', 'EV Charging', 'BBQ Area'], bookingDetails: { minStay: 12, maxStay: 365, checkIn: '2:00 PM', checkOut: '12:00 PM', cancellationPolicy: '30-day notice required.', securityDeposit: 168000, extraCharges: 'Pool maintenance Rs.4000/month.', houseRules: ['No events without approval'] }, aiDescription: '4BHK villa in Gurgaon — 30% off with lifetime rent lock.', images: [{ url: 'https://images.unsplash.com/photo-1570129477492-45a003537e1b?w=800&h=600&fit=crop&q=80' }, { url: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop&q=80' }] },
      { title: 'Urban Studio Pod — Pay for 11, Get 12 Months', description: 'Connaught Place studio with Murphy bed and 500 Mbps WiFi. Pay 11 get 12 free every year.', propertyType: 'studio', status: 'available', isVerified: true, price: { amount: 22000, currency: 'INR', period: 'monthly' }, offer: { isActive: true, label: '🎁 Pay 11 Months, Get 12th Free — Every Year', discountPercent: 8, originalPrice: 24000, badge: 'FAN FAVOURITE' }, location: { address: 'F-12 Inner Circle, Connaught Place', city: 'Delhi', state: 'Delhi', pincode: '110001', coordinates: { lat: 28.6315, lng: 77.2167 } }, features: { bedrooms: 0, bathrooms: 1, area: 380, furnished: 'fully-furnished', parking: false, petFriendly: false }, amenities: ['500 Mbps WiFi', 'Murphy Bed', 'Smart Storage', 'AC', 'Concierge', 'Metro Access'], bookingDetails: { minStay: 1, maxStay: 365, checkIn: '11:00 AM', checkOut: '11:00 AM', cancellationPolicy: 'Free cancellation 5 days before', securityDeposit: 22000, extraCharges: '12th month free on annual lease.', houseRules: ['No smoking', 'Quiet hours 11 PM to 7 AM'] }, aiDescription: 'Micro-studio at Connaught Place — pay 11 get 12 months free.', images: [{ url: 'https://images.unsplash.com/photo-1493857671505-72967e2e2760?w=800&h=600&fit=crop&q=80' }, { url: 'https://images.unsplash.com/photo-1527482797697-8795b1a55a45?w=800&h=600&fit=crop&q=80' }] },
      { title: 'Heritage Haveli Suite — 35% Below Market, Always', description: '3-bedroom suite in a 200-year-old restored haveli. 35% below market — permanent price promise.', propertyType: 'apartment', status: 'available', isVerified: true, price: { amount: 38000, currency: 'INR', period: 'monthly' }, offer: { isActive: true, label: '🏛 35% Off Market Rate — Permanent Promise', discountPercent: 35, originalPrice: 58500, badge: 'RARE FIND' }, location: { address: 'Haveli No. 3, Chandpol Bazaar', city: 'Jaipur', state: 'Rajasthan', pincode: '302001', coordinates: { lat: 26.9124, lng: 75.7873 } }, features: { bedrooms: 3, bathrooms: 2, area: 2100, furnished: 'fully-furnished', parking: true, petFriendly: false }, amenities: ['Courtyard', 'Fountain', 'Heritage Architecture', 'Rooftop Terrace', 'WiFi', 'AC', 'Concierge'], bookingDetails: { minStay: 3, maxStay: 365, checkIn: '2:00 PM', checkOut: '11:00 AM', cancellationPolicy: '50% refund if cancelled 10 days before', securityDeposit: 76000, extraCharges: 'Utilities included.', houseRules: ['No nails or alterations', 'No loud music'] }, aiDescription: 'Haveli suite in Jaipur — 35% below market, permanent price.', images: [{ url: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&h=600&fit=crop&q=80' }, { url: 'https://images.unsplash.com/photo-1576941089067-2de3dd21bfb0?w=800&h=600&fit=crop&q=80' }] },
      { title: 'Lakeside Condo — Free Parking + 22% Off Forever', description: 'Hussain Sagar lakeside condo with floor-to-ceiling windows. 22% off + free parking, locked in forever.', propertyType: 'condo', status: 'available', isVerified: true, price: { amount: 42000, currency: 'INR', period: 'monthly' }, offer: { isActive: true, label: '💎 22% Off + Free Parking Forever — Member Perk', discountPercent: 22, originalPrice: 54000, badge: 'MEMBER DEAL' }, location: { address: '5 Lakeview Residences, Tank Bund Road', city: 'Hyderabad', state: 'Telangana', pincode: '500080', coordinates: { lat: 17.4239, lng: 78.4738 } }, features: { bedrooms: 2, bathrooms: 2, area: 1250, furnished: 'fully-furnished', parking: true, petFriendly: true }, amenities: ['Lake View', 'Wrap-Around Balcony', 'Infinity Pool', 'Gym', 'WiFi', 'Covered Parking', 'Jogging Track'], bookingDetails: { minStay: 3, maxStay: 365, checkIn: '2:00 PM', checkOut: '11:00 AM', cancellationPolicy: 'Free cancellation 10 days before', securityDeposit: 84000, extraCharges: 'Parking free. Utilities: Rs.2500-3500/month.', houseRules: ['No smoking indoors', 'Jogging track: 5 AM to 10 PM'] }, aiDescription: 'Lakeside condo on Hussain Sagar — 22% off with free parking.', images: [{ url: 'https://images.unsplash.com/photo-1512207736139-c1957dd8ded5?w=800&h=600&fit=crop&q=80' }, { url: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&h=600&fit=crop&q=80' }] },
    ];

    const seededProperties = [];
    for (const prop of propertiesData) {
      prop.owner = landlordId;
      const existing = await Property.findOne({ title: prop.title });
      if (!existing) {
        const created = await Property.create(prop);
        seededProperties.push(created);
      } else if (prop.offer && (!existing.offer || !existing.offer.isActive)) {
        existing.offer = prop.offer;
        await existing.save();
        seededProperties.push(existing);
      }
    }
    console.log('✅ Auto-seeded / updated ' + seededProperties.length + ' properties.');

    const mockComments = ['Stunning place! Extremely clean.', 'Very convenient location. Top-notch amenities.', 'Great experience. Excellent security.', 'Absolutely loved staying here!', 'Clean, modern, very comfortable.', 'All features as advertised. Would book again.'];
    let reviewCount = 0;
    for (const property of seededProperties) {
      const reviewers = tenantIds.slice(0, Math.floor(Math.random() * 2) + 2);
      let totalRating = 0;
      for (const tenantId of reviewers) {
        const rating = Math.floor(Math.random() * 2) + 4;
        await Review.create({ property: property._id, user: tenantId, rating, comment: mockComments[Math.floor(Math.random() * mockComments.length)] });
        totalRating += rating;
        reviewCount++;
      }
      await Property.findByIdAndUpdate(property._id, { averageRating: Math.round((totalRating / reviewers.length) * 10) / 10, totalReviews: reviewers.length });
    }
    console.log('✅ Auto-seeded ' + reviewCount + ' reviews.');
    console.log('🎉 Auto-seed complete!');
  } catch (err) {
    console.error('❌ Auto-seed error:', err.message);
  }
};

module.exports = autoSeed;
